services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - app

  redis:
    image: redis:6.2.5

  producer:
    build: ./producer
    depends_on:
      - redis
    deploy:
      replicas: 2

  app:
    build: ./app
    deploy:
      replicas: 4
      endpoint_mode: dnsrr
