services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
    depends_on:
      - app

  app:
    build: ./app
    deploy:
      replicas: 4
      endpoint_mode: dnsrr
